vrpn_client_node:
  ros__parameters:
    server: '192.168.88.13'
    port: '3883'
    update_frequency: 25.0
    frame_id: 'world'
    use_server_time: False
    broad_cast_tf: True
    refresh_tracker_frequency: 1.0