# Ubuntu 20.04
FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

# setup entrypoint
COPY ./entrypoint.sh /

# Standard package
RUN apt-get update && apt-get install -y git vim wget curl byobu zip unzip

# install ros and build tools
ENV ROS_DISTRO foxy
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
RUN apt update && apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN apt install -y software-properties-common
RUN add-apt-repository -y universe 
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt update && apt install -y ros-$ROS_DISTRO-ros-base python3-argcomplete python3-colcon-common-extensions python3-rosdep

# Python dependencies
RUN apt-get install -y python3-pip python3-tk

# Install python package
RUN pip3 install --upgrade pip
RUN pip3 install hydra-core omegaconf mujoco

# Other thirdparty python packages
WORKDIR /home/thirdparty
RUN git clone https://github.com/AntoineRichard/rl_games.git
WORKDIR /home/thirdparty/rl_games
RUN pip3 install -e .

# fix python lib
RUN pip3 install numpy==1.21 opencv-python==4.5.5.64

# Get realsense driver for jetson
RUN apt-key adv --keyserver keyserver.ubuntu.com \
--recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
--recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
RUN apt-get install -y librealsense2-utils librealsense2-dev

# Get extra ros packages
RUN apt-get install -y \
ros-$ROS_DISTRO-vrpn-mocap
# ros-$ROS_DISTRO-realsense2-*

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]