FROM dustynv/pytorch:1.11-r35.2.1

# Standard package
RUN apt-get update && apt-get install -y git vim wget curl byobu zip unzip

# Python dependencies
RUN apt-get install -y python3-tk

# Python package
RUN pip3 install --upgrade pip
RUN pip3 install hydra-core omegaconf mujoco

# setup entrypoint
COPY ./entrypoint.sh /

# Other thirdparty python packages
WORKDIR /home/thirdparty
RUN git clone https://github.com/AntoineRichard/rl_games.git
WORKDIR /home/thirdparty/rl_games
RUN pip3 install -e .

# Get realsense driver for jetson
RUN apt-key adv --keyserver keyserver.ubuntu.com \
--recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
--recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u
RUN apt-get install -y librealsense2-utils librealsense2-dev

# Install ros and build tools
ENV ROS_DISTRO foxy
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt install ros-$ROS_DISTRO-desktop python3-argcomplete
RUN apt-get install -y python3-colcon-common-extensions python3-rosdep

# Get extra ros packages
RUN apt-get install -y \
ros-$ROS_DISTRO-vrpn-mocap \
ros-$ROS_DISTRO-realsense2-*

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]