FROM osrf/ros:foxy-desktop

# Standard package
RUN apt-get update && apt-get install -y git vim wget curl byobu zip unzip

# ROS build dependencies
RUN apt-get update && apt-get install -y python3-colcon-common-extensions python3-rosdep

# Python dependencies
RUN apt-get install -y python3-pip python3-tk

# Python package
RUN pip3 install hydra-core omegaconf mujoco

# setup entrypoint
COPY ./entrypoint.sh /

# Other thirdparty python packages
WORKDIR /home/thirdparty
RUN git clone https://github.com/AntoineRichard/rl_games.git
WORKDIR /home/thirdparty/rl_games
RUN pip3 install -e .

# extra ROS packages
ENV ROS_DISTRO foxy
RUN apt install -y \
ros-$ROS_DISTRO-realsense2-* \
ros-$ROS_DISTRO-vrpn-mocap

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]