# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ${resolve_default:${task.name},${task.experiment}}

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# whether to use cpu or gpu physx
sim_device: 'gpu'
# used for gpu simulation only - device id for running sim and task if pipeline=gpu
device_id: 0
# device to run RL
rl_device: 'cuda:0'
# multi-GPU training
multi_gpu: False

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

# used to set checkpoint path
checkpoint: ''

wandb_activate: False
use_rl: True

ros:
  state_pose_topic: /spacer_floating_platform/FP_B/pose
  # state_pose_topic: /spacer_floating_platform/FP_exp_RL/pose
  goal_pose_topic: /spacer_floating_platform/FP_exp_RL/pose
  # goal_pose_topic: /spacer_floating_platform/FP_B/pose
  action_topic: /spacer_floating_platform/valves/input

platform:
  map: [0, 1, 2, 3, 4, 5, 6, 7] #jetson
  # map: [2, 5, 4, 7, 6, 1, 0, 3] #rpi4

# set default task and default training config based on task
defaults:
  - _self_
  - task: virtual_floating_platform/MFP2D_Virtual_GoToXY
  - train: virtual_floating_platform/MFP2D_PPOmulti_dict_MLP
  - controller: Optimal_LQR_DC
  - hl_task: GoToXY_Square
  - overrride hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .